# Generated by Django 5.1 on 2024-09-11 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_user_cartitem_username_remove_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
