// Desc: User Constants

//user login
export const USER_REQUEST_LOGIN = 'USER_REQUEST';
export const USER_REQUEST_LOGIN_SUCCESFUL = 'USER_REQUEST_LOGIN_SUCCESFUL';
export const USER_REQUEST_LOGIN_FAILED = 'USER_REQUEST_LOGIN_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';
// vendor registration
export const USER_REQUEST_REGISTER = 'USER_REQUEST_REGISTER';
export const USER_REQUEST_REGISTER_SUCCESFUL = 'USER_REQUEST_REGISTER_SUCCESFUL';
export const USER_REQUEST_REGISTER_FAILED = 'USER_REQUEST_REGISTER_FAILED';